<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>VubChat.Server</RootNamespace>
    <AssemblyName>VubChat.Server</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ApplicationUseCompatibleTextRendering>false</ApplicationUseCompatibleTextRendering>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VubChat.Zajednicki\VubChat.Zajednicki.csproj" />
  </ItemGroup>

</Project>
